Update messages.gotext.json
koho/frpmgr pull request #136
Opened 2024-03-27 02:59 UTC by Neo1102

2024-03-27 15:58 UTC, koho requested changes

2024-03-27 15:58 UTC, koho commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "請求表頭"
“表頭” 是否應為 “標頭” ？

2024-03-27 15:58 UTC, koho commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "前往者"
這裡翻譯是不是有問題，它的本意是作為客戶端訪問其他計算機的服務。

2024-03-27 15:58 UTC, koho commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "複製前往位址"
和 Visitor 類似。

2024-03-27 18:37 UTC, Neo1102 commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "請求表頭"
如果這裡指是封包的Headers，那翻成表頭是正確的

2024-03-27 18:42 UTC, Neo1102 commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "前往者"
抱歉，這是校訂的疏失，另外請問一下，這邊的Visitor是用在什麼情境下的呢?

2024-03-27 18:48 UTC, Neo1102 commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "複製前往位址"
我修正為 "複製存取位址" 了，謝謝

2024-03-28 07:24 UTC, koho commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "前往者"
這邊的 Visitor 和 Client 比较接近，在用戶端-伺服器架構中扮演用戶端訪問其他計算機的服務。可以理解为 Visitor 等於 Client-server 架構中的 Client。

2024-03-28 07:35 UTC, Neo1102 commented on i18n/locales/zh-TW/messages.gotext.json
> +            "translation": "前往者"
了解，已修正為"訪客"，謝謝

2024-03-28 07:48 UTC, koho approved these changes

2024-03-28 07:50 UTC, merged